import jsPDF from 'jspdf';
import { format } from 'date-fns';

const loadLogo = async (url) => {
  if (!url) return null;
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'Anonymous';
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = url;
  });
};

export const generateExperienceCertificate = async ({ teacher, institute }) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  
  const logoImg = await loadLogo(institute?.logo_url || institute?.logo);
  const primaryColor = [15, 23, 42]; // Slate 900
  const accentColor = [59, 130, 246]; // Blue 500
  
  // Header background
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, 210, 40, 'F');
  
  // Logo
  if (logoImg) {
    doc.addImage(logoImg, 'PNG', 15, 8, 24, 24);
  }
  
  // Institute Name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(26);
  doc.setTextColor(...primaryColor);
  const instituteName = institute?.name || 'THE CLOUDS ACADEMY';
  doc.text(instituteName.toUpperCase(), logoImg ? 45 : 15, 22);
  
  // Tagline/Address
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(institute?.address || '123 Academic Block, City, Country', logoImg ? 45 : 15, 30);
  
  // Decorative line
  doc.setDrawColor(...accentColor);
  doc.setLineWidth(1);
  doc.line(15, 45, 195, 45);

  // Certificate Title
  doc.setFont('times', 'bolditalic');
  doc.setFontSize(32);
  doc.setTextColor(...primaryColor);
  doc.text('Experience Certificate', 105, 75, { align: 'center' });

  // Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`Date: ${format(new Date(), 'dd MMMM, yyyy')}`, 160, 95);

  // Body text
  doc.setFontSize(14);
  doc.setLineHeightFactor(1.8);
  
  const fullName = `${teacher.first_name || ''} ${teacher.last_name || ''}`.trim();
  const designation = teacher.details?.teacherDetails?.designation || 'Teacher';
  const joiningDate = teacher.details?.teacherDetails?.joining_date;
  
  const formattedJoiningDate = joiningDate ? format(new Date(joiningDate), 'dd MMMM yyyy') : '[Joining Date]';
  
  const bodyText = `This is to certify that Mr./Ms. ${fullName} has been a dedicated employee at ${instituteName}. They have served the institution in the capacity of ${designation} since ${formattedJoiningDate}.

During their tenure, we have found them to be hardworking, highly professional, and deeply committed to the academic growth of their students. Their conduct has been exemplary, and they have significantly contributed to the betterment of the institution.

We wish them all the best in their future endeavors.`;

  const splitText = doc.splitTextToSize(bodyText, 170);
  doc.text(splitText, 20, 120);

  // Signatures Area
  const sigY = 220;
  
  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.line(20, sigY, 80, sigY);
  doc.line(130, sigY, 190, sigY);
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Principal', 50, sigY + 8, { align: 'center' });
  doc.text('Administrator', 160, sigY + 8, { align: 'center' });

  // Footer
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text(`Generated by TCA Management System`, 105, 285, { align: 'center' });
  
  doc.save(`${fullName.replace(/\s+/g, '_')}_Experience_Certificate.pdf`);
};
